### ISSUE TITLE
Many populist_dictatorships have the wrong flag

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [ccfox/CWE-FoxFork#103]
Brazil, Catalonia, Chile, Colombia, European Union, Italy, North Germany, Spain, the UK etc. have populist_dictatorships with fascist flags.

**Comment by ccfox** [comment]
Yeah, it seems to be kind of randomly assigned with no real consistency. Not helping matters is that both are reversed in files and in loc.
