### ISSUE TITLE
Archive time?

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [ccfox/CWE-FoxFork#107]
@ccfox contributions have stopped and OpenVic2 or Project Alice seem to be better places to spend effort.

**Comment by ccfox** [comment]
Project Alice, as per its devs, are not focusing on moddability at the moment - especially not for things outside of the scope of the base-game. Their priority is getting the game to actually function at least at the same capacity as Victoria II before then seeing what they can do (they aren't adding new ideologies, new mechanics, etc). I am a writer by trade as well, and not a programmer, so there isn't really anything I can add for them at this stage - nor do I think they are raking in any money to be able to hire my services.


I have a job and obligations irl. Me being mostly inactive for a few months does not mean the project is abandoned, that I've forgotten about it, or that it will not receive any future attention. It means I am busy, and simply haven't had the time. Any further questions regarding private matters, such as why I haven't been adding as much lately, should be directed towards my personal Discord account - which can be found on the public CWE server.

**Comment by Outta-my-way-burrocrat** [comment]
@ccfox 
>I have a job and obligations irl. Me being mostly inactive for a few months does not mean the project is abandoned, that I've forgotten about it, or that it will not receive any future attention. It means I am busy, and simply haven't had the time. Any further questions regarding private matters, such as why I haven't been adding as much lately, should be directed towards my personal Discord account - which can be found on the public CWE server.

By the tone in your message, I guess I've offended you; I am sorry. I did not intend to comment on any events in your life, and do not think you did wrong by prioritizing any issues in your life over modding.
