### ISSUE TITLE
[Offtopic modding] Could you playtest a prototype mod?

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [ccfox/CWE-FoxFork#109]
@ccfox I've worked on a mostly-vanilla rebalance mod here: https://github.com/Outta-my-way-burrocrat/Communist_changes_fork nobody but me and the scraping bots have downloaded it. Could you take a look at it? I'm probably gonna add the social-liberal ideology to it sometime soon.

**Comment by ccfox** [comment]
Run into any economy issues from this? "Cavalry requires cattle"

**Comment by Outta-my-way-burrocrat** [comment]
I added that without testing it. I'll need to do that.

**Comment by Outta-my-way-burrocrat** [comment]
https://github.com/Outta-my-way-burrocrat/Communist_changes_fork/issues

**Comment by Outta-my-way-burrocrat** [comment]
I've moved the cavalry changes out of main; are there any issues?

**Comment by ccfox** [comment]
Any issues are likely to be with the ai than player economy side. The only real way to tell would be to do a whole lot of games and see if the ai struggles. As far as player goes, the main issue is that iirc military is usually a huge drain.

**Comment by Outta-my-way-burrocrat** [comment]
Gonna close this so it doesnt steal attention

**Comment by ccfox** [comment]
Alright. Have you thought about making a discord account by the way?

**Comment by Outta-my-way-burrocrat** [comment]
It would be very nice to have better messaging than whats available through GitHub, but no; I don't trust Discord, so I won't use it. I will message you if I see you elsewhere.

**Comment by ccfox** [comment]
Do you have a paradox account?
