### ISSUE TITLE
I'm going to stop contributing

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [ccfox/CWE-FoxFork#115]
I want to be clear, I'm not stopping because of you or settintotrieste, but I'm going to stop posting code here on the 28th. Thanks for collaborating with me.

**Comment by ccfox** [comment]
Alright. I appreciate all the help you've provided thus far.

**Comment by ccfox** [comment]
Sure, though I don't know if I will be able to add to/update it.

**Comment by Outta-my-way-burrocrat** [comment]
Transfer started, and I sent a message your way.

**Comment by Outta-my-way-burrocrat** [comment]
Any problems with the transfer?

**Comment by ccfox** [comment]
It doesn't show up under my repos, but I assume I have access to it?

**Comment by Outta-my-way-burrocrat** [comment]
If I read the docs correctly, GitHub should've sent you a confirmation email which allows you to choose to accept control of the repo or not.

**Comment by ccfox** [comment]
Okay, got it.

**Comment by Outta-my-way-burrocrat** [comment]
@ccfox @settintotrieste Before I shut down, I'll leave a link to a geography project hosted on GitHub (I don't endorse it I thought it might be worth checking out) https://github.com/aourednik/historical-basemaps
