### ISSUE TITLE
Project Alice's collaborators

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [ccfox/CWE-FoxFork#118]
@ccfox @settintotrieste Project Alice is publicly collaborating with DoktorKure's MHM to make their mod compatible. Have y'all been approached by them?

**Comment by ccfox** [comment]
Yes, they are in the discord.

**Comment by Outta-my-way-burrocrat** [comment]
@ccfox @settintotrieste do y'all plan to work with schombert's team to make CWE and FoxFork compatible with Project Alice?
