### ISSUE TITLE
UK foreign investment bug

### ISSUE THREAD

**Issue by FixDis** [ccfox/CWE-FoxFork#125]
First attempted fix https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/pull/1199

https://github.com/ccfox/CWE-FoxFork/blob/3ba0cbb0cf53abd9062c5e85d5591e6fc52805f6/CWEFanFork/history/units/ENG_oob.txt#L1

**Comment by ccfox** [comment]
Where is it _supposed_ to go?

**Comment by FixDis** [comment]
in history/ENG - United Kingdom

**Comment by FixDis** [comment]
I'm sorry I forgot to mention one foreign_investment entry in history/units/1950/ENG_oob.txt: https://github.com/ccfox/CWE-FoxFork/blob/2d0c41d0aee90ce545f88ac803755da44a0cf0c3/CWEFanFork/history/units/1950/ENG_oob.txt#L1
