### ISSUE TITLE
[CWE] Factory bugs

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [ccfox/CWE-FoxFork#36]
[Too many optics factories](https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/issues/986) What is the purpose of all 94 optics-glass factories in the mod? They are always going bankrupt every game. 2105; 1346; 1386; 1391; 1392; 1624; 2509; 619; 623; 641; 873; 46; 1485; 1508; 2221; 425; 438; 442; 451; 534; 553; 570; 586; 589; 599; 603; 605; 2576; 720; 739; etc..

Too many glass factories, and some missing glass factories in places like New York, Alsace-Lorraine and Munster.

communications_factory shouldn't be in these provinces until the factory is unlocked: 1624; 619; 46; 1485; 451; 553; 589; 599; 2576; 1649; 2142; 322; 343.

No integrated_circuits factories anywhere.

No pharmaceuticals_factory in France, Germany, or anywhere outside Arkansas.

**Comment by ccfox** [comment]
I can't find the excess factories?

**Comment by Outta-my-way-burrocrat** [comment]
They aren't exceeding the state factory limit but they aren't ever solvent. Here's a link to three of the factories: https://github.com/ccfox/CWE-FoxFork/blob/ce825189096ae6bec35a679c8aba2704e2b8f231/CWEFanFork/history/provinces/asia/1624%20-%20Seoul.txt#L32

**Comment by Outta-my-way-burrocrat** [comment]
Germany should have more inorganic chemical factories
