### ISSUE TITLE
[CWE] Some countries don't have any primary culture pops

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [ccfox/CWE-FoxFork#38]
https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/issues/849

>Many commonwealth pops are switched from English to British and vice versa in 1992.

**Comment by Outta-my-way-burrocrat** [comment]
Panama lacks primary culture rich pops before 1992.

**Comment by Outta-my-way-burrocrat** [comment]
This PR didn't change any pops in 1992:

https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/commit/ed20ef4ebc09ad8a81c92e5ff28f0e847ebdd3b3

**Comment by ccfox** [comment]
The 1992 start is cursed. I'm not even sure how Panama doesn't have any primary culture pops - but I'm fairly confident most of the pop figures and demographics are wrong or based on nwo (or even the mod that came before that). They need a complete review at some point.

**Comment by Outta-my-way-burrocrat** [comment]
Khuzestan is missing primary culture pops in 1992
