### ISSUE TITLE
Market socialsit became less popular even if i promove them

### ISSUE THREAD

**Issue by Santiago2710** [ccfox/CWE-FoxFork#50]
Market socialsit became less popular even if i promove them
![Captura de pantalla (673)](https://user-images.githubusercontent.com/98244959/230799330-ecea8f5d-4229-4a6e-bbe2-8642ce14c3e4.png)

**Comment by ccfox** [comment]
Do you mean the national focus, or the decision?

**Comment by Santiago2710** [comment]
both, the campaing deccision don´t work for governament (how are the market socialist in my case) propaganda and the focus donsen´t make any effect, market socialist became less and less popular no mather how i promove the ideology, the governament propaganda or political issues that my market socialis party have.

**Comment by ccfox** [comment]
The focus only increases electoral support, but the decisions for campaigning should increase actual ideology. I'll look into things and see why it might not be working.

**Comment by ccfox** [comment]
This should now be fixed.
