### ISSUE TITLE
(CWE) Curacao ships are named after Latvian ships

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [ccfox/CWE-FoxFork#67]
https://github.com/ccfox/CWE-FoxFork/blob/aac9a9d31406f1fc13cca999a32842d927375ca5/CWEFanFork/common/countries/Curacao.txt#L128
https://github.com/ccfox/CWE-FoxFork/blob/aac9a9d31406f1fc13cca999a32842d927375ca5/CWEFanFork/common/countries/Latvia.txt#L359

**Comment by ccfox** [comment]
It should be fixed now.
